[package]
name = "Bass-machine"
version = "0.2.0"
authors = ["rasmu"]
edition = "2018"

[dependencies]
vst = { git = "https://github.com/rust-dsp/rust-vst" }
hound = "3.4.0"

[dependencies.wavetable]
path = "../wavetable"

[lib]
name = "bass_machine"
crate-type = ["cdylib"]
