[package]
name = "wavetable"
version = "0.1.0"
authors = ["Will Tange <will@brt.sexy>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
either = "1.5.2"
hound = "3.4.0"
lazy_static = "1.4.0"
rand = "0.7.3"